# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Juan Pampin
email: juan@pampin.org
description: >- # this means to ignore newlines until "baseurl:"
  site documenting artistic & research work by Juan Pampin.
# twitter_username: username
github_username: pampin
# minimal_mistakes_skin: default
minimal_mistakes_skin: dark
search: true

# added by JP
locale: "en-US"
# title_separator: "|"
subtitle: "Art / Technology & Ideas"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - _portfolio

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Juan Pampin"
  avatar : "/assets/images/juanphoto01.jpg"
  bio    : "Art / Technology & Ideas"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pampin"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://dxarts.washington.edu/"
    - label: "Instagram"  
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/dxarts"

# footer:
#   links:
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: "https://github.com/pampin"
#     - label: "Website"
#       icon: "fas fa-fw fa-link"
#       url: "https://dxarts.washington.edu/"
#     - label: "Instagram"  
#       icon: "fab fa-fw fa-instagram"
#       url: "https://instagram.com/dxarts"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      # layout: single
      layout: splash
      author_profile: false
      read_time: false
      comments: false
      share: true
      related: true
      # JP
      show_date: false
      read_time: false

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      # layout: single
      layout: splash
      author_profile: false

  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: splash
      author_profile: false
      share: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections:
  works:
    output: true
    permalink: /:collection/:path/
